version: '3.8'

services:
  sdi-site:
    image: ghcr.io/veteranoql69/new_site_sdi:v2
    # ports:
    #   - "4000:3000"
    environment:
      - NODE_ENV=production
      - N8N_WEBHOOK_URL=https://sdiwebhook.sditecnologia.cl/webhook/78795bc4-b573-4565-a885-525f6bdd3109
      - CONTACT_FORM_WEBHOOK_URL=https://sdiwebhook.sditecnologia.cl/webhook/sdi_formulario
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.sdi-site.rule=Host(`sditecnologia.cl`) || Host(`www.sditecnologia.cl`)"
        - "traefik.http.routers.sdi-site.entrypoints=websecure"
        - "traefik.http.routers.sdi-site.tls.certresolver=letsencryptresolver"
        - "traefik.http.routers.sdi-site.tls=true"
        - "traefik.http.services.sdi-site.loadbalancer.server.port=3000"
    networks:
      - DesaNet

networks:
  DesaNet:
    external: true
    name: DesaNet
